BookProject/Components/CartSummaryViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookProject.Models;
using Microsoft.AspNetCore.Mvc;

namespace BookProject.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;
        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

BookProject/Components/TypesViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BookProject.Models;

namespace BookProject.Components
{
    public class TypesViewComponent : ViewComponent
    {
        private IBookProjectRepository repo { get; set; }

        public TypesViewComponent (IBookProjectRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedType = RouteData?.Values["category"]; // ? means it's ok if there is no category in the url, it's nullable
            var types = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);
            return View(types);
        }
    }
}

BookProject/Views/Shared/BookSummary.cshtml
@model Book
<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>@Model.Title</h4>
        
        <span class="badge bg-info" style="float:right">
            Price: $@Model.Price
        </span>
    </div>

        <ul>
            <li>Author: @Model.Author</li>
            <li>Publisher: @Model.Publisher</li>
            <li>ISBN: @Model.Isbn</li>
            <li>Category: @Model.Category</li>
            <li>Classification: @Model.Classification</li>
            <li>Number of Pages: @Model.PageCount Pages</li>            
        </ul>

<form method="post" asp-page="/Shop">
    <input type="hidden" asp-for="@Model.BookId" />
    <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()"/>
    <span class="card-text">
        <button type="submit" class="btn btn-success btn-sm float-end">Add to cart</button>
    </span>
</form>
</div>

BookProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/css/bootstrap-grid.css" rel="stylesheet" />
    <link href="~/lib/css/bootstrap-reboot.css" rel="stylesheet" />
    <link href="~/lib/css/bootstrap-utilities.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-1/css/all.min.css" integrity="sha512-ZYg+hQvLlM0W9C3P6vTpes5LmJ66G2EsroxDNzwD6qiulckldb29eD9I672HL2X+LH5nRhY1sQqZLJGB+aUUPg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                    <span class="col navbar-brand ml-2">Book Nation</span>
                <div class="col-6 text-right">
                    <vc:cart-summary />
                </div>
            </div>
        </div>
    </div>
    <div class="row m-1 p-1">
        <div id="categories" class="col-3">
            <vc:types></vc:types>
        </div>
        <div class="col-9">
            @RenderBody()
        </div>
    </div>

    <footer>Book Nation Inc.</footer>
</body>
</html>